@props(['products', 'categories'])

<div class="new-products-section-modern">
    <div class="container px-3 px-md-3">
        
        <!-- Section Header -->
        <div class="section-header text-center mb-3">
            
            <h2 class="section-title fw-bold mb-3">Discover New Products</h2>
            <p class="section-subtitle text-muted">Explore our latest collection of premium products</p>
        </div>

        <!-- Category Filter Pills -->
        <div class="category-filter-wrapper mb-3">
            <div class="category-scroll-container">
                <ul class="nav nav-pills category-pills gap-2" id="productCategoryTabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active rounded-pill" 
                                id="all-tab" 
                                data-bs-toggle="tab" 
                                data-bs-target="#all" 
                                type="button" 
                                role="tab"
                                aria-controls="all" 
                                aria-selected="true"
                                data-category="all">
                            <i class="bi bi-grid-3x3-gap me-2"></i>All Products
                        </button>
                    </li>
                    @foreach($categories as $index => $category)
                        <li class="nav-item" role="presentation">
                            <button class="nav-link rounded-pill" 
                                    id="cat-{{ $index }}-tab" 
                                    data-bs-toggle="tab" 
                                    data-bs-target="#cat-{{ $index }}" 
                                    type="button" 
                                    role="tab"
                                    aria-controls="cat-{{ $index }}" 
                                    aria-selected="false"
                                    data-category="{{ $category }}">
                                <i class="bi bi-tag me-2"></i>{{ ucfirst($category) }}
                            </button>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>

        <!-- Products Grid with Tabs -->
        <div class="tab-content" id="productCategoryTabContent">
            <!-- All Products Tab -->
            <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
                <div class="products-grid" data-products-container="all">
                    @foreach($products as $product)
                        <div class="product-item">
                            <x-kartu-produk 
                                :id="$product['id']"
                                :name="$product['name']" 
                                :price="$product['price']" 
                                :image="$product['image']"
                                :badge=" null"
                                :oldPrice="$product['oldPrice'] ?? null"
                                :category="$product['category']"
                                :brand="$product['brand'] ?? null"
                            />
                        </div>
                    @endforeach
                </div>
                
                <!-- Pagination for All Products -->
                @if(count($products) > 12)
                <div class="pagination-wrapper mt-5" data-pagination="all">
                    <nav aria-label="Products pagination">
                        <ul class="pagination justify-content-center flex-wrap gap-1">
                            <li class="page-item disabled" data-page-prev>
                                <a class="page-link rounded-circle" href="#" aria-label="Previous">
                                    <i class="bi bi-chevron-left"></i>
                                </a>
                            </li>
                            <!-- Pages will be generated by JavaScript -->
                            <li class="page-item disabled" data-page-next>
                                <a class="page-link rounded-circle" href="#" aria-label="Next">
                                    <i class="bi bi-chevron-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="text-center mt-3">
                        <small class="text-muted" data-pagination-info>
                            Showing <span class="fw-semibold" data-showing-start>1</span>-<span class="fw-semibold" data-showing-end>12</span> of <span class="fw-semibold" data-total-items>{{ count($products) }}</span> products
                        </small>
                    </div>
                </div>
                @endif
            </div>

            <!-- Category Tabs -->
            @foreach($categories as $index => $category)
                <div class="tab-pane fade" id="cat-{{ $index }}" role="tabpanel" aria-labelledby="cat-{{ $index }}-tab">
                    @php
                        $filteredProducts = array_filter($products, fn($p) => $p['category'] === $category);
                    @endphp
                    
                    @if(count($filteredProducts) > 0)
                        <div class="products-grid" data-products-container="cat-{{ $index }}">
                            @foreach($filteredProducts as $product)
                                <div class="product-item">
                                    <x-kartu-produk
                                        :id="$product['id']" 
                                        :name="$product['name']" 
                                        :price="$product['price']" 
                                        :image="$product['image']"
                                        :badge=" null"
                                        :oldPrice="$product['oldPrice'] ?? null"
                                        :category="$product['category']"
                                        :brand="$product['brand'] ?? null"
                                    />
                                </div>
                            @endforeach
                        </div>
                        
                        <!-- Pagination for Category -->
                        @if(count($filteredProducts) > 12)
                        <div class="pagination-wrapper mt-5" data-pagination="cat-{{ $index }}">
                            <nav aria-label="Products pagination">
                                <ul class="pagination justify-content-center flex-wrap gap-1">
                                    <li class="page-item disabled" data-page-prev>
                                        <a class="page-link rounded-circle" href="#" aria-label="Previous">
                                            <i class="bi bi-chevron-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item disabled" data-page-next>
                                        <a class="page-link rounded-circle" href="#" aria-label="Next">
                                            <i class="bi bi-chevron-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                            <div class="text-center mt-3">
                                <small class="text-muted" data-pagination-info>
                                    Showing <span class="fw-semibold" data-showing-start>1</span>-<span class="fw-semibold" data-showing-end>12</span> of <span class="fw-semibold" data-total-items>{{ count($filteredProducts) }}</span> products
                                </small>
                            </div>
                        </div>
                        @endif
                    @else
                        <div class="no-products text-center py-5">
                            <i class="bi bi-inbox display-1 text-muted mb-3"></i>
                            <p class="text-muted fs-5">No products available in this category</p>
                        </div>
                    @endif
                </div>
            @endforeach
        </div>

        <!-- View All Button -->
        <div class="text-center mt-5">
            <a href="/products" class="btn btn-primary btn-lg rounded-pill px-4 shadow-sm">
                <span>View All Products</span>
                <i class="bi bi-arrow-right ms-2"></i>
            </a>
        </div>

    </div>
</div>

<style>
/* Modern New Products Section */
.new-products-section-modern {
    padding: 5rem 0;
    position: relative;
}

.new-products-section-modern::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 300px;
    background: radial-gradient(circle at top center, rgba(13, 110, 253, 0.05) 0%, transparent 70%);
    pointer-events: none;
}

/* Section Header */
.section-header {
    position: relative;
    z-index: 1;
}

.section-title {
    font-size: 2.75rem;
    color: #212529;
    letter-spacing: -0.5px;
}

.section-subtitle {
    font-size: 1.125rem;
    max-width: 600px;
    margin: 0 auto;
}

/* Category Pills */
.category-filter-wrapper {
    margin-bottom: 1.5rem;
}

.category-scroll-container {
    overflow-x: auto;
    overflow-y: hidden;
    -webkit-overflow-scrolling: touch; /* Smooth scroll iOS */
    scrollbar-width: none; /* Hide scrollbar Firefox */
    -ms-overflow-style: none; /* Hide scrollbar IE/Edge */
    padding: 10px 5px;
}

/* Hide scrollbar Chrome/Safari */
.category-scroll-container::-webkit-scrollbar {
    display: none;
}

.category-pills {
    display: flex;
    flex-wrap: nowrap;
    justify-content: center; /* Centered seperti sebelumnya */
    gap: 0.5rem;
    list-style: none;
    padding: 0;
    margin: 0;
    width: max-content;
    min-width: 100%; /* Agar tetap center jika items sedikit */
}

.category-pills .nav-item {
    flex-shrink: 0;
}

.category-pills .nav-link {
    white-space: nowrap;
    padding: 0.5rem 1.25rem;
    transition: all 0.3s ease;
}

/* Products Grid */
.products-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    min-height: 400px;
    position: relative;
}

.product-item {
    animation: fadeInUp 0.5s ease-out backwards;
    width: 100%;
}

.product-item:nth-child(1) { animation-delay: 0.05s; }
.product-item:nth-child(2) { animation-delay: 0.1s; }
.product-item:nth-child(3) { animation-delay: 0.15s; }
.product-item:nth-child(4) { animation-delay: 0.2s; }

@keyframes fadeInUp {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

/* Pagination Styles */
.pagination-wrapper {
    position: relative;
    z-index: 1;
}

.pagination {
    margin-bottom: 0;
}

.pagination .page-link {
    border: 1px solid #dee2e6;
    color: #6c757d;
    font-weight: 500;
    padding: 0.5rem 0.75rem;
    margin: 0 0.125rem;
    transition: all 0.3s ease;
    min-width: 40px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
}

.pagination .page-link.rounded-circle {
    width: 40px;
    height: 40px;
    padding: 0;
    border-radius: 50% !important;
}

.pagination .page-link:hover {
    background: #f8f9fa;
    border-color: #0d6efd;
    color: #0d6efd;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(13, 110, 253, 0.15);
}

.pagination .page-item.active .page-link {
    background: linear-gradient(135deg, #0d6efd 0%, #0a58ca 100%);
    border-color: #0d6efd;
    color: #ffffff;
    box-shadow: 0 4px 16px rgba(13, 110, 253, 0.3);
}

.pagination .page-item.disabled .page-link {
    background: #f8f9fa;
    border-color: #dee2e6;
    color: #adb5bd;
    opacity: 0.6;
}

/* No Products State */
.no-products i {
    opacity: 0.3;
}

/* View All Button */
.btn-primary {
    font-weight: 600;
    transition: all 0.3s ease;
    position: relative;
    overflow: hidden;
}

.btn-primary::before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 0;
    height: 0;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.2);
    transform: translate(-50%, -50%);
    transition: width 0.6s ease, height 0.6s ease;
}

.btn-primary:hover::before {
    width: 300px;
    height: 300px;
}

.btn-primary:hover {
    transform: translateY(-3px);
    box-shadow: 0 8px 24px rgba(13, 110, 253, 0.3) !important;
}

.btn-primary i {
    transition: transform 0.3s ease;
}

.btn-primary:hover i {
    transform: translateX(4px);
}

/* Tab Pane Animation */
.tab-pane {
    animation: fadeIn 0.4s ease-out;
}

@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

/* Loading State */
.products-grid.loading {
    opacity: 0.5;
    pointer-events: none;
}

.products-grid.loading::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 40px;
    height: 40px;
    margin: -20px 0 0 -20px;
    border: 3px solid #f3f3f3;
    border-top: 3px solid #0d6efd;
    border-radius: 50%;
    animation: spin 1s linear infinite;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}

/* ======================================
   RESPONSIVE STYLES
   ====================================== */

/* Tablet */
@media (max-width: 991px) {
    .section-title {
        font-size: 2.25rem;
    }
    
    .category-pills {
        flex-wrap: nowrap;
    }

    .products-grid {
        grid-template-columns: repeat(3, 1fr);
        gap: 1.25rem;
    }
}

/* Mobile */
@media (max-width: 768px) {
    .new-products-section-modern {
        padding: 3rem 0;
    }

    .section-title {
        font-size: 1.875rem;
    }

    .section-subtitle {
        font-size: 1rem;
    }

    .category-pills {
    justify-content: flex-start; /* Align left di mobile */
    min-width: auto;
    }

    .category-filter-wrapper {
        margin-bottom: 1.5rem;
    }

    .category-pills .nav-link {
        padding: 0.5rem 1.25rem;
        font-size: 0.875rem;
    }

    .products-grid {
        grid-template-columns: repeat(2, 1fr);
        gap: 1rem;
        min-height: 300px;
    }

    .pagination .page-link {
        padding: 0.375rem 0.625rem;
        min-width: 36px;
        height: 36px;
        font-size: 0.875rem;
    }

    .pagination .page-link.rounded-circle {
        width: 36px;
        height: 36px;
    }
}

/* Small Mobile */
@media (max-width: 480px) {
    .new-products-section-modern {
        padding: 2rem 0;
    }

    .section-header .badge {
        font-size: 0.8125rem;
    }

    .section-title {
        font-size: 1.625rem;
    }

    .section-subtitle {
        font-size: 0.9375rem;
    }

    .category-pills .nav-link {
        padding: 0.5rem 1rem;
        font-size: 0.8125rem;
    }

    .category-pills .nav-link i {
        font-size: 0.75rem;
    }

    .products-grid {
        grid-template-columns: repeat(2, 1fr);
        gap: 0.875rem;
    }

    .pagination .page-link {
        padding: 0.25rem 0.5rem;
        min-width: 32px;
        height: 32px;
        font-size: 0.8125rem;
    }

    .pagination .page-link.rounded-circle {
        width: 32px;
        height: 32px;
    }

    .btn-primary {
        width: 100%;
        max-width: 280px;
    }
}

/* Smooth scrolling for category tabs */
@media (max-width: 991px) {
    .category-filter-wrapper {
        scroll-behavior: smooth;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Configuration - CHANGED FROM 12 TO 10
    const ITEMS_PER_PAGE = 12;
    
    // Initialize pagination for each tab
    const paginationWrappers = document.querySelectorAll('[data-pagination]');
    
    paginationWrappers.forEach(wrapper => {
        const category = wrapper.getAttribute('data-pagination');
        const productsContainer = document.querySelector(`[data-products-container="${category}"]`);
        const productItems = productsContainer.querySelectorAll('.product-item');
        
        if (productItems.length > ITEMS_PER_PAGE) {
            initPagination(category, productItems, wrapper);
        }
    });
    
    function initPagination(category, items, wrapper) {
        const totalItems = items.length;
        const totalPages = Math.ceil(totalItems / ITEMS_PER_PAGE);
        let currentPage = 1;
        
        const pagination = wrapper.querySelector('.pagination');
        const prevBtn = wrapper.querySelector('[data-page-prev]');
        const nextBtn = wrapper.querySelector('[data-page-next]');
        const infoText = wrapper.querySelector('[data-pagination-info]');
        const startSpan = infoText.querySelector('[data-showing-start]');
        const endSpan = infoText.querySelector('[data-showing-end]');
        const totalSpan = infoText.querySelector('[data-total-items]');
        
        // Generate page buttons
        function generatePageButtons() {
            // Remove old page buttons
            const oldButtons = pagination.querySelectorAll('.page-item:not([data-page-prev]):not([data-page-next])');
            oldButtons.forEach(btn => btn.remove());
            
            // Calculate page range to show
            let startPage = Math.max(1, currentPage - 2);
            let endPage = Math.min(totalPages, startPage + 4);
            
            if (endPage - startPage < 4) {
                startPage = Math.max(1, endPage - 4);
            }
            
            // Insert before next button
            const nextBtnLi = pagination.querySelector('[data-page-next]');
            
            // Add first page and ellipsis if needed
            if (startPage > 1) {
                createPageButton(1, nextBtnLi);
                if (startPage > 2) {
                    createEllipsis(nextBtnLi);
                }
            }
            
            // Add page buttons
            for (let i = startPage; i <= endPage; i++) {
                createPageButton(i, nextBtnLi);
            }
            
            // Add ellipsis and last page if needed
            if (endPage < totalPages) {
                if (endPage < totalPages - 1) {
                    createEllipsis(nextBtnLi);
                }
                createPageButton(totalPages, nextBtnLi);
            }
        }
        
        function createPageButton(pageNum, insertBefore) {
            const li = document.createElement('li');
            li.className = 'page-item' + (pageNum === currentPage ? ' active' : '');
            
            const a = document.createElement('a');
            a.className = 'page-link';
            a.href = '#';
            a.textContent = pageNum;
            a.setAttribute('aria-label', `Go to page ${pageNum}`);
            
            a.addEventListener('click', function(e) {
                e.preventDefault();
                goToPage(pageNum);
            });
            
            li.appendChild(a);
            pagination.insertBefore(li, insertBefore);
        }
        
        function createEllipsis(insertBefore) {
            const li = document.createElement('li');
            li.className = 'page-item disabled';
            
            const span = document.createElement('span');
            span.className = 'page-link';
            span.textContent = '...';
            
            li.appendChild(span);
            pagination.insertBefore(li, insertBefore);
        }
        
        function showPage(page) {
            const start = (page - 1) * ITEMS_PER_PAGE;
            const end = start + ITEMS_PER_PAGE;
            
            items.forEach((item, index) => {
                if (index >= start && index < end) {
                    item.style.display = '';
                    item.style.animation = 'fadeInUp 0.5s ease-out backwards';
                    item.style.animationDelay = `${(index - start) * 0.05}s`;
                } else {
                    item.style.display = 'none';
                }
            });
            
            // Update pagination info
            startSpan.textContent = start + 1;
            endSpan.textContent = Math.min(end, totalItems);
            totalSpan.textContent = totalItems;
            
            // Update button states
            prevBtn.classList.toggle('disabled', page === 1);
            nextBtn.classList.toggle('disabled', page === totalPages);
            
            // Scroll to top of products section smoothly
            const sectionTop = document.querySelector('.new-products-section-modern').offsetTop;
            window.scrollTo({
                top: sectionTop -  0,
                behavior: 'smooth'
            });
        }
        
        function goToPage(page) {
            currentPage = page;
            showPage(currentPage);
            generatePageButtons();
        }
        
        // Event listeners
        prevBtn.addEventListener('click', function(e) {
            e.preventDefault();
            if (currentPage > 1) {
                goToPage(currentPage - 1);
            }
        });
        
        nextBtn.addEventListener('click', function(e) {
            e.preventDefault();
            if (currentPage < totalPages) {
                goToPage(currentPage + 1);
            }
        });
        
        // Initialize
        generatePageButtons();
        showPage(currentPage);
    }
    
    // Reset pagination when switching tabs
    const tabButtons = document.querySelectorAll('.category-pills .nav-link');
    tabButtons.forEach(button => {
        button.addEventListener('shown.bs.tab', function(e) {
            const targetId = e.target.getAttribute('data-bs-target').replace('#', '');
            const category = e.target.getAttribute('data-category');
            
            // Scroll active tab into view on mobile
            if (window.innerWidth <= 991) {
                e.target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'nearest',
                    inline: 'center'
                });
            }
            
            // Reset pagination for the active tab
            const paginationWrapper = document.querySelector(`[data-pagination="${targetId}"]`);
            if (paginationWrapper) {
                const productsContainer = document.querySelector(`[data-products-container="${targetId}"]`);
                const productItems = productsContainer.querySelectorAll('.product-item');
                
                if (productItems.length > ITEMS_PER_PAGE) {
                    initPagination(targetId, productItems, paginationWrapper);
                }
            }
        });
    });
    
    // Scroll active tab into view on load (mobile)
    const activeTab = document.querySelector('.category-pills .nav-link.active');
    if (activeTab && window.innerWidth <= 991) {
        setTimeout(() => {
            activeTab.scrollIntoView({
                behavior: 'smooth',
                block: 'nearest',
                inline: 'center'
            });
        }, 100);
    }
});
</script>